CREATE TABLE IF NOT EXISTS bank_account (
id INT GENERATED BY DEFAULT AS IDENTITY,
bic text,
iban text,
account text,
bank text,
branch text,
country text,
country_iso text,
city text,
state text,
zip text,
address text,
description text,
chart_id integer,
inactive boolean
);

UPDATE defaults SET fldvalue = '2.8.32' where fldname = 'version';