CREATE TABLE IF NOT EXISTS bank_account (
id INT GENERATED BY DEFAULT AS IDENTITY,
bic varchar(11),
iban varchar(255),
account varchar(255),
bank varchar(255),
branch varchar(255),
country varchar(32),
country_iso varchar(2),
city varchar(128),
state varchar(128),
zip varchar(11),
address varchar(128)
);

UPDATE defaults SET fldvalue = '2.8.32' where fldname = 'version';