CREATE TABLE IF NOT EXISTS banking_export_event
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status             TEXT      NOT NULL,
    bank_account_id    INT REFERENCES bank_account (id),
    source_id          INT       NOT NULL, -- paymentId
    source_type        TEXT      NOT NULL, -- RMA_PAYMENT
    source_data        JSONB     NOT NULL, -- paymentPayload
    exported_when      TIMESTAMP NOT NULL,
    is_manual          BOOLEAN   NOT NULL,
    export_id          TEXT      NOT NULL  -- submissionId
);

CREATE TABLE blink_export_process
(
    id               SERIAL PRIMARY KEY,
    bank_account_id  BIGINT REFERENCES bank_account (id) NOT NULL,
    process_type     TEXT                                NOT NULL,
    status           TEXT                                NOT NULL,
    error            JSONB,
    created_at       TIMESTAMP                           NOT NULL,
    last_modified_at TIMESTAMP
);

CREATE TABLE blink_export_process_log
(
    id                      SERIAL PRIMARY KEY,
    blink_export_process_id BIGINT REFERENCES blink_export_process (id) NOT NULL,
    processed_target_id     TEXT                                        NOT NULL, -- messageId/paymentId OR submissionId
    processed_payload       JSONB                                       NOT NULL, -- messagePayload OR submissionResponse
    error                   JSONB,
    banking_export_event_id BIGINT REFERENCES banking_export_event (id)
);


UPDATE defaults SET fldvalue = '2.8.45' WHERE fldname = 'version';