-- Schweizer Kontenrahmen KMU (Sterchi/Schweizer Gewerbeverband)
-- exkl. Konzern- und Tochtergesellschaften
-- ab SQL Ledger Version 2.8, einsprachig (englisch)
-- Das Script löscht den bestehenden Kontenrahmen (falls vorhanden). 
-- Dieses Script nur bei Neuinstallationen bzw. Datenbanken ohne bestehende Buchungen durchführen.
-- Version 05.12.2014 Neues Rechnungslegungsrecht, Thomas Brändle, Mattia Kienast, Nils Samuelsson

-----------------
--- 1 AKTIVEN ---
-----------------
DELETE FROM chart;
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1','ASSETS','H','A','','1',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('10','CURRENT ASSETS','H','A','','100',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('100','CASH AND SECURITIES','H','A','','100',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1000','Cash','A','A','AR_paid:AP_paid','100',false,true,'kassa');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1020','Bank','A','A','AR_paid:AP_paid','100',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values  ('109','TRANSFER ACCOUNTS','H','A','','109',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1090','Transfer Account','A','A','AR_paid:AP_paid','109',false,true,'transfer');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1099','Clarification account','A','A','AP_amount','109',false,true,'abklärung');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('110','ACCOUNTS RECEIVABLE','H','A','','110',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1100','Accounts Receivable Switzerland','A','A','AR','110',false,false,'forderungenschweiz');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1101','Accounts Receivable Foreign Countries','A','A','AR','110',false,false,'forderungenauslandchf');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1102','Accounts Receivable Foreign Currencies','A','A','AR','110',false,false,'forderungenauslandandere');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1103','Accounts receivable old','A','A','','110',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1109','Value Adjustments Accounts Receivable','A','A','','110',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('111','ACCOUNTS RECEIVABLE INVESTMENTS','H','A','','111',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1110','Accounts Receivable Investments','A','A','','111',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('114','OTHER ACCOUNTS RECEIVABLE','H','A','','114',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('115','OTHER ACCOUNTS REICEIVABLE THIRD PARTIES','H','A','','115',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('117','ACCOUNTS RECEIVABLE PUBLIC AGENCIES','H','A','','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1177','Accounts Receivable Customs Office','A','A','','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1179','Withholding Tax','A','A','','117',false,true,'verrechnungssteuer');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('118','ACCOUNTS RECEIVABLE SOCIAL INSURANCE','H','A','','118',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('119','OTHER CURRENT RECEIVABLES','H','A','','119',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1192','Advance Payments','A','A','AP_paid','109',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('120','INVENTORY','H','A','','120',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1280','Work in Progress','A','A','IC','120',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('130','ACCRUALS','H','A','','130',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1300','Accrued cost','A','A','','130',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1301','Accrued income','A','A','','130',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('14','FIXED ASSETS','H','A','','140',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('140','INVESTMENTS','H','A','','140',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1400','Investment securities','A','A','','140',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('144','LONG TERM RECEIVABLES THIRD PARTIES','H','A','','144',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1440','Loans Third Parties','A','A','','144',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('145','LONG TERM RECEIVABLES INVESTMENTS','H','A','','145',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1450','Loans Investments','A','A','','145',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('148','SHARES','H','A','','148',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1480','Shares','A','A','','148',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('150','TANGIBLE ASSETS','H','A','','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1500','Machinery and apparatus','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1510','Mobile fixed assets','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1520','Office Mashines and Hardware','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1530','Cars','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1540','Tools and equipment','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1590','Other Tangible Assets','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('160','IMMOBILE SACHANLAGEN','H','A','','160',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1600','Immobile Sachanlagen','A','A','','160',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('170','INTANGIBLE ASSETS','H','A','','170',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1700','Patents, Brands','A','A','AP_amount','170',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1741','Software','A','A','AP_amount','170',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1790','Other Immaterial Goods','A','A','','170',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2','EQUITY AND LIABILITIES','H','L','','2',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('20','SHORT-TERM DEBT','H','L','','200',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('200','ACCOUNTS PAYABLE','H','L','','200',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2000','Accounts payable','A','L','AP','200',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2001','Accounts payable old','A','L','','200',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2002','Liabilities Personnel','A','L','','200',false,true,'lohnzahlung');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('203','ADVANCES','H','L','','203',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2030','Advances from Third Parties','A','L','AR_amount:IC_income','203',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('210','SHORT-TERM FINANCIAL LIABILITIES','H','L','','210',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('214','SHORT-TERM FINANCIAL LIABILITIES THIRD PARTIES','H','L','','214',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('215','SHORT-TERM FINANCIAL LIABILITIES INVESTMENTS','H','L','','215',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('220','SHORT-TERM FINANCIAL LIABILITIES INVESTMENTS PUBLIC AGENCIES','H','L','','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2200','VAT payable','A','L','AP_amount','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2206','Withholding Tax','A','L','AP_amount','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('221','SHORT-TERM FINANCIAL LIABILITIES THIRD PARTIES (INTEREST-FREE)','H','L','','221',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2215','Kreditkarte','A','L','','221',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('225','SHORT-TERM FINANCIAL LIABILITIES INVESTMENTS (INTEREST-FREE)','H','L','','225',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('227','SHORT-TERM FINANCIAL LIABILITIES SOCIAL INSURANCE (INTEREST-FREE)','H','L','','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2270','Current Account Pension Fund','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2271','Current Account AHV, IV, EO, ALV','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2272','Current Account FAK','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2273','Current Account Accident Insurance ','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2274','Current Account sickness insurance','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2279','Current Account Source Tax','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('230','DEFERRED AND CURRENT PROVISIONS','H','L','','230',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2300','Accrued Cost','A','L','','230',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2301','Accrued Income','A','L','','230',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2330','Accrued Liabilities','A','L','','230',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('24','LONG TERM DEBT','H','L','','240',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('240','LONG TERM DEBT (INTEREST BEARING)','H','L','','240',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2400','Long-term Bank Debt','A','L','','240',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('245','OTHER LONG TERM DEBT THIRD PARTIES (INTEREST BEARING)','H','L','','245',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('247','OTHER LONG TERM DEBT INVESTMENTS (INTEREST BEARING)','H','L','','247',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('250','OTHER LONG TERM DEBT THIRD PARTIES (INTEREST-FREE)','H','L','','250',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('255','OTHER LONG TERM DEBT INVESTMENTS (INTEREST-FREE)','H','L','','255',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('260','LONG TERM PROVISIONS','H','L','','260',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2600','Provisions','A','L','','260',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3','REVENUES','H','I','','3',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('30','REVENUES FROM PRODUCTION','H','I','','300',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3000','Revenues Production','A','I','AR_amount:IC_income','300',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('32','REVENUES FROM TRADE','H','I','','320',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3200','Revenues Trade','A','I','AR_amount:IC_income','320',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('34','REVENUES FROM SERVICES','H','I','','340',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3400','Revenues Services','A','I','AR_amount:IC_income','340',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('36','OTHER REVENUES','H','I','','360',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3600','Incidental Revenue','A','I','AR_amount:IC_income','360',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3680','Other Revenues','A','I','AR_amount:IC_income','360',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3689','Not Assigned','A','I','AR_amount','360',false,true,'nichtkontierterertrag');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3699','Systemaccount','A','I','AR_amount:IC_sale:IC_income','360',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('37','GOODS ON OWN ACCOUNT','H','I','','370',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3700','Goods on Own Account','A','I','','370',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3710','Internal Consumption','A','I','','370',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('38','REDUCTION IN EARNINGS','H','I','','380',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3800','Allowance','A','I','AR_paid','380',false,true,'debitorskonto');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3801','Discounts','A','I','AR_paid','380',false,true,'debitordifferenz');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3804','Collection Expense','A','I','','380',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3805','Loss on loans','A','I','AR_amount:IC_income','380',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('39','INVENTORY CHANGE','H','I','','390',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3900','Inventory Change Unfinished Goods','A','I','','390',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3901','Inventory Change Finished Goods','A','I','','390',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3904','Inventory Change Uncharged Services','A','I','','390',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4','EXPENSES','H','E','','400',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('40','EXPENSES FOR PRODUCTION','H','E','','400',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4000','Expenses for Production','A','E','AP_amount','400',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('42','EXPENSES FOR TRADE','H','E','','420',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4200','Expenses for Trade','A','E','AP_amount','420',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('44','EXPENSES FOR SERVICES','H','E','','440',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4400','Expenses for Service','A','E','AP_amount','440',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('45','ENERGY FOR GOODS AND SERVICES','H','E','','450',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('46','OTHER DIRECT EXPENSES','H','E','','460',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('48','INVENTORY CHANGE LOSS OF MATERIAL','H','E','','480',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4800','Inventory Change Trade','A','E','','480',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4880','Inventory Change Material','A','E','','480',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('49','PURCHASE PRICE REDUCTION','H','E','','490',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4999','Systemaccount','A','E','AP_amount:IC_expense:IC_cogs','490',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5','PERSONNEL COSTS','H','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5400','Wages','A','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5401','Gratification','A','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5402','Profit Sharing','A','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5403','Bonus','A','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5405','Benefits from Social Insurance','A','E','AP_amount','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('57','SOCIAL INSURANCE COSTS ','H','E','','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5700','AHV, IV, EO, ALV','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5710','FAK','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5720','Pension Fund','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5730','Accident Insurance','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5740','Sick Pay Insurance','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5790','Withholding Tax','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('58','OTHER PERSONNEL COSTS','H','E','','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5800','Recruiting','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5810','Education and training','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5820','Effective Expenses','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5830','Lump-sum Expenses','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5840','Internal Food / Beverages','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5880','Other personnel expenses','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5890','Private Part Personal Costs','A','E','','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('59','EFFORTS THIRD PARTIES','H','E','','590',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5900','Efforts Third Parties','A','E','AP_amount','590',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6','OTHER OPERATING EXPENSES','H','E','','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('60','HOUSING COSTS','H','E','','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6000','Rent','A','E','AP_amount','600',false,true,'miete');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6030','Related Costs','A','E','AP_amount','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6040','Cleaning','A','E','AP_amount','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6090','Private Part Housing Costs','A','E','','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('61','MAINTENANCE, REPAIR, REPLACEMENT AND LEASING OF TANGIBLE ASSETS','H','E','','610',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6130','Maintenance and Replacement Office Materials','A','E','AP_amount','610',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6160','Leasing','A','E','AP_amount','610',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('62','VEHICLE AND TRANSPORTATION EXPENSES','H','E','','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6200','Repair, Service, Cleaning Vehicles','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6210','Fuel','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6220','Insurance Vehicles','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6230','Transport Charges, Fees, Charges','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6260','Vehicle Leasing','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6270','Private Part Vehicles','A','E','AR_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6280','Logistics','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('63','INSURANCE','H','E','','630',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6300','Insurance','A','E','AP_amount','630',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6360','Duties','A','E','AP_amount','630',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6370','Permits','A','E','AP_amount','630',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('64','ENERGY, WASTE','H','E','','640',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6400','Electricity','A','E','AP_amount','640',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6460','Disposal Costs (Waste)','A','E','AP_amount','640',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('65','ADMINISTRATION AND INFORMATION TECHNOLOGY EXPENSES','H','E','','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('650','ADMINISTRATION EXPENSES','H','E','','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6500','Office Supplies, Printing, Copies','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6501','Printed Papers','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6503','Literature','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6510','Telecommunications','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6513','Postage','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6520','Contribution, Donations, etc.','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6530','Accounting Costs','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6531','Management Consultancy','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6532','Legal Advice','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6540','Shareholders Meeting','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6542','Audit Cost','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6550','Organizational Costs','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6551','Collection Costs','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('657','INFORMATION TECHNOLOGY EXPENSES','H','E','','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6570','Leasing Hardware and Software','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6580','Licenses, Updates','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6581','Hosting and Maintenance','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6583','IT Consumables','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6590','IT Consulting and Development','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('66','MARKETING EXPENSES','H','E','','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6600','Advertising','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6610','Advertising Material, Promotional Material, Samples','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6620','Trade Fairs, Exhibitions, Decoration','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6640','Travel Expenses','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6641','Client Expenses','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6660','Sponsoring','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6670','Public Relations, Customer Events','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6680','Market Research, Advertising Services','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('67','OTHER OPERATING EXPENSES','H','E','','670',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6700','Other Operating Expenses','A','E','AP_amount','670',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6799','Not Assigned','A','E','AP_amount','670',false,true,'nichtkontierteraufwand');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('68','FINANCIAL INCOME AND EXPENSES','H','E','','680',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6800','Valuation Adjustment','A','E','','680',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6820','Depreciation','A','E','','680',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('690','FINANCIAL EXPENSES','H','E','','690',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6900','Interest Cost Third Parties','A','E','AP_amount','690',false,true,'schuldzins');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6930','Interest Cost Pension Fund','A','E','AP_amount','690',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6940','Bank Expenses','A','E','AR_paid:AP_paid','690',false,true,'drittspesen');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6942','Exchange Loss','A','E','','690',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6943','Credit Card Costs','A','E','AP_amount','690',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6944','Bank Expenses','A','E','AP_paid','690',false,true,'kreditordifferenz');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('695','FINANCIAL INCOME','H','E','','695',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6950','Financial Income','A','E','','695',false,true,'guthabenzins');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6952','Exchange Profit','A','E','','695',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('7','OPERATIONAL ANCILLARY RESULTS','H','E','','700',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('700','REVENUES FROM COMPANION PLANTS','H','E','','700',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('7000','Revenues form Companion Plants','A','E','','700',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('701','EXPENSES COMPANION PLANTS','H','E','','701',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('7010','Expenses Companion Plants','A','E','','701',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8','EXTRAORDINARY AND NON-OPERATING EXPENSES, TAX','H','E','','800',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('800','NON-OPERATING EXPENSES','H','E','','800',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8000','Non-Operationg Expenses','A','E','','800',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('810','NON-OPERATING REVENUES','H','E','','810',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8100','Non-Operationg Revenues','A','E','','810',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('850','EXTRAORDNIARY EXPENSES','H','E','','850',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8500','Extraordinary Expenses','A','E','','850',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('851','EXTRAORDNIARY REVENUES','H','E','','851',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8510','Extraordinary Revenues','A','E','','851',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('860','NONRECURRING EXPENSES','H','E','','860',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8600','Nonrecurring Expenses','A','E','','860',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('861','NONRECURRING REVENUES','H','E','','861',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8610','Nonrecurring Revenues','A','E','','861',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('870','EXPENSES FOR OTHER ACCOUNTING PERIODS','H','E','','870',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8700','Expenses for Other Accounting Periods','A','E','','870',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('871','REVENUES FOR OTHER ACCOUNTING PERIODS','H','E','','871',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8710','Revenues for Other Accounting Periods','A','E','','871',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('89','DIRECT TAX','H','E','','890',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8900','Canton and Community Tax','A','E','AP_amount','890',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8901','Federal Tax','A','E','AP_amount','890',false,true,'');

insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('112','ACCOUNTS RECEIVABLE SHAREHOLDERS','H','A','','112',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1120','Accounts Receivable Shareholders','A','A','','112',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('116','OTHER ACCOUNTS RECEIVABLE SHAREHOLDERS','H','A','','116',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('146','LONG TERM RECEIVABLES SHAREHOLDERS','H','A','','146',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1460','Shareholder Loans','A','A','','146',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('216','SHORT-TERM FINANCIAL LIABILITIES INVESTMENTS SHAREHOLDERS','H','L','','216',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2160','Current Account Shareholder','A','L','AR_paid:AP_paid','216',false,true,'kontokorrent');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('226','OTHER SHORT-TERM FINANCIAL LIABILITIES INVESTMENTS SHAREHOLDERS (INTEREST-FREE)','H','L','','226',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2261','Decided Profit Distribution','A','L','','226',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('248','LONG-TERM FINANCIAL LIABILITIES INVESTMENTS SHAREHOLDERS','H','L','','248',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('256','OTHER LONG-TERM FINANCIAL LIABILITIES INVESTMENTS SHAREHOLDERS (INTEREST-FREE)','H','L','','256',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('28','EQUITY','H','Q','','280',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('280','CAPITAL','H','Q','','280',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2800','Capital','A','Q','','280',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('290','RETAINED EARNINGS / LOSS OF BALANCE','H','Q','','290',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2900','Agio','A','Q','','290',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2950','Legal Reserves','A','Q','','290',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2960','Other Reserves','A','Q','','290',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('297','ACCUMULATED PROFITS','H','Q','','297',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2970','Accumulated Profits','A','Q','','297',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2979','Annual Earnings','A','Q','','297',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('298','OWN SHARES','H','Q','','298',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2980','Own Shares','A','Q','','298',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6920','Interest Cost Shareholders','A','E','AP_amount','690',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1170','Input VAT 8.0% on Mat. + Serv.','A','A','AP_tax','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1172','Input VAT 2.5% on Mat. + Serv.','A','A','AP_tax','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1173','Input VAT 8.0% on Inv. + Oth. Exp.','A','A','AP_tax','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1174','Input VAT 3.8% on Inv. + Oth. Exp.','A','A','AP_tax','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1175','Input VAT 2.5% on Inv. + Oth. Exp.','A','A','AP_tax','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1176','Input VAT 8,0% Reverse Charge','A','A','AP_tax','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2201','VAT 8,0%','A','L','AR_tax:IC_taxpart:IC_taxservice','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2202','VAT 3,8%','A','L','','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2203','VAT 2,5%','A','L','','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2204','Reverse Charge 8,0%','A','L','AP_tax','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('22050','VAT Exports 0% (Ziff. 220)','A','L','','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('22051','VAT Services Abroad 0% (Ziff. 221)','A','L','','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('22052','VAT Non Taxable Services 0% (Ziff. 230)','A','L','','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('22053','VAT Subsidies 0% (Ziff. 900)','A','L','','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('22054','VAT Donations, Dividends, Compensations 0% (Ziff. 910)','A','L','','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('22055','VAT Nichtentgelt 0%','A','L','','220',false,true,'');

---
DELETE FROM tax;
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '1170'),0.080);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '1172'),0.025);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '1173'),0.080);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '1174'),0.038);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '1175'),0.025);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '1176'),0.08);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '2201'),0.080);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '2202'),0.038);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '2203'),0.025);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '2204'),0.08);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '22050'),0.00);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '22051'),0.00);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '22052'),0.00);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '22053'),0.00);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '22054'),0.00);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '22055'),0.00);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '2206'),0.00);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '6730'),0.08);
--
DELETE FROM DEFAULTS WHERE fldname='inventory_accno_id';
DELETE FROM DEFAULTS WHERE fldname='income_accno_id';
DELETE FROM DEFAULTS WHERE fldname='expense_accno_id';
DELETE FROM DEFAULTS WHERE fldname='fxgain_accno_id';
DELETE FROM DEFAULTS WHERE fldname='fxloss_accno_id';
DELETE FROM DEFAULTS WHERE fldname='currencies';
DELETE FROM DEFAULTS WHERE fldname='weightunit';
DELETE FROM DEFAULTS WHERE fldname='cdt';
DELETE FROM DEFAULTS WHERE fldname='precision';
DELETE FROM DEFAULTS WHERE fldname='glnumber';
DELETE FROM DEFAULTS WHERE fldname='sinumber';
DELETE FROM DEFAULTS WHERE fldname='vinumber';
DELETE FROM DEFAULTS WHERE fldname='batchnumber';
DELETE FROM DEFAULTS WHERE fldname='vouchernumber';
DELETE FROM DEFAULTS WHERE fldname='sonumber';
DELETE FROM DEFAULTS WHERE fldname='ponumber';
DELETE FROM DEFAULTS WHERE fldname='sqnumber';
DELETE FROM DEFAULTS WHERE fldname='rfqnumber';
DELETE FROM DEFAULTS WHERE fldname='partnumber';
DELETE FROM DEFAULTS WHERE fldname='employeenumber';
DELETE FROM DEFAULTS WHERE fldname='customernumber';
DELETE FROM DEFAULTS WHERE fldname='vendornumber';
DELETE FROM DEFAULTS WHERE fldname='projectnumber';
DELETE FROM DEFAULTS WHERE fldname='audittrail';
INSERT INTO defaults (fldname, fldvalue) VALUES ('inventory_accno_id', (SELECT id FROM chart WHERE accno = '1280'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '3400'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '4200'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '6952'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '6942'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('weightunit', 'kg');
INSERT INTO defaults (fldname, fldvalue) VALUES ('precision', '2');
INSERT INTO DEFAULTS (fldname, fldvalue) VALUES ('cdt', '1');
INSERT INTO defaults (fldname, fldvalue) VALUES ('glnumber','X-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('sinumber','R-999');
INSERT INTO defaults (fldname, fldvalue) VALUES ('vinumber','EB-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('batchnumber','V-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('vouchernumber','B-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('sonumber','AB-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('ponumber','E-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('sqnumber','O-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('rfqnumber','EO-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('partnumber','ART-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('employeenumber','MA-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('customernumber','KD-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('vendornumber','L-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('projectnumber','P-0');
INSERT INTO defaults (fldname, fldvalue) VALUES ('audittrail','1');

--
DELETE FROM curr;
INSERT INTO curr (rn, curr, precision) VALUES (1,'CHF',2);
INSERT INTO curr (rn, curr, precision) VALUES (2,'EUR',2);
INSERT INTO curr (rn, curr, precision) VALUES (3,'USD',2);
INSERT INTO curr (rn, curr, precision) VALUES (4,'GBP',2);
INSERT INTO curr (rn, curr, precision) VALUES (5,'JPY',2);
INSERT INTO curr (rn, curr, precision) VALUES (6,'CAD',2);
INSERT INTO curr (rn, curr, precision) VALUES (7,'AUD',2);
INSERT INTO curr (rn, curr, precision) VALUES (8,'CNY',2);
INSERT INTO curr (rn, curr, precision) VALUES (9,'SGD',2);
INSERT INTO curr (rn, curr, precision) VALUES (10,'HKD',2);
INSERT INTO curr (rn, curr, precision) VALUES (11,'SEK',2);
INSERT INTO curr (rn, curr, precision) VALUES (12,'DKK',2);
INSERT INTO curr (rn, curr, precision) VALUES (13,'NOK',2);
INSERT INTO curr (rn, curr, precision) VALUES (14,'PLN',2);
INSERT INTO curr (rn, curr, precision) VALUES (15,'RUB',2);
INSERT INTO curr (rn, curr, precision) VALUES (16,'RSD',2);
INSERT INTO curr (rn, curr, precision) VALUES (17,'TRY',2);

UPDATE chart SET allow_gl = false WHERE accno IN ('1100','1101','1102','2000');
