-- Diverse Anpassungen durch Run my Accounts AG, Juni, September 2008, Oktober 2010
-- Version 23.10.2010, Thomas BrändleINSERT INTO gifi (accno,description) VALUES ('1','AKTIVEN');
INSERT INTO gifi (accno,description) VALUES ('1', 'AKTIVEN');
INSERT INTO gifi (accno,description) VALUES ('2', 'PASSIVEN');
INSERT INTO gifi (accno,description) VALUES ('3', 'BETRIEBSERTRAG AUS LIEFERUNGEN UND LEISTUNGEN');
INSERT INTO gifi (accno,description) VALUES ('4', 'AUFWAND FÜR MATERIAL, WAREN UND DIENSTLEISTUNGEN');
INSERT INTO gifi (accno,description) VALUES ('5', 'PERSONALAUFWAND');
INSERT INTO gifi (accno,description) VALUES ('6', 'SONSTIGER BETRIEBSAUFWAND');
INSERT INTO gifi (accno,description) VALUES ('8', 'AUSSERORDENTLICHER UND BETRIEBSFREMDER ERFOLG, STEUERN');
INSERT INTO gifi (accno,description) VALUES ('9', 'TRANSFERKONTEN');
INSERT INTO gifi (accno,description) VALUES ('100', 'Flüssige Mittel und Wertschriften');
INSERT INTO gifi (accno,description) VALUES ('110', 'Forderungen');
INSERT INTO gifi (accno,description) VALUES ('120', 'Angefangene Arbeiten');
INSERT INTO gifi (accno,description) VALUES ('130', 'Aktive Rechnungsabgrenzung');
INSERT INTO gifi (accno,description) VALUES ('140', 'Finanzanlagen');
INSERT INTO gifi (accno,description) VALUES ('150', 'Mobile Sachanlagen, IT');
INSERT INTO gifi (accno,description) VALUES ('160', 'Immobile Sachanlage');
INSERT INTO gifi (accno,description) VALUES ('170', 'Immaterielle Anlagen');
INSERT INTO gifi (accno,description) VALUES ('180', 'Aktivierter Aufwand');
INSERT INTO gifi (accno,description) VALUES ('190', 'Betriebsfremdes Vermögen');
INSERT INTO gifi (accno,description) VALUES ('200', 'Kurzfristige Verbindlichkeiten aus Lieferungen & Leistungen');
INSERT INTO gifi (accno,description) VALUES ('210', 'Kurzfristige Finanzverbindlichkeiten');
INSERT INTO gifi (accno,description) VALUES ('220', 'Andere kurzfristige Finanzverbindlichkeiten');
INSERT INTO gifi (accno,description) VALUES ('230', 'Transitorische Passiven');
INSERT INTO gifi (accno,description) VALUES ('240', 'Langfristige Finanzverbindlichkeiten');
INSERT INTO gifi (accno,description) VALUES ('260', 'Rückstellungen');
INSERT INTO gifi (accno,description) VALUES ('270', 'Betriebsfremde Verbindlichkeiten');
INSERT INTO gifi (accno,description) VALUES ('280', 'Eigenkapital');
INSERT INTO gifi (accno,description) VALUES ('290', 'Reserven');
INSERT INTO gifi (accno,description) VALUES ('299', 'Bilanzgewinn / Bilanzverlust');
INSERT INTO gifi (accno,description) VALUES ('300', 'Produktionsertrag');
INSERT INTO gifi (accno,description) VALUES ('320', 'Handelsertrag');
INSERT INTO gifi (accno,description) VALUES ('340', 'Dienstleistungsertrag');
INSERT INTO gifi (accno,description) VALUES ('360', 'Übriger Ertrag');
INSERT INTO gifi (accno,description) VALUES ('370', 'Eigenleistung und Eigenverbrauch');
INSERT INTO gifi (accno,description) VALUES ('380', 'Bestandesänderung angefangene und fertiggestellte Arbeiten aus Produktion und Dienstleistungen');
INSERT INTO gifi (accno,description) VALUES ('390', 'Ertragsminderungen');
INSERT INTO gifi (accno,description) VALUES ('400', 'Materialaufwand');
INSERT INTO gifi (accno,description) VALUES ('420', 'Handelswarenaufwand');
INSERT INTO gifi (accno,description) VALUES ('440', 'Aufwand für Drittleistungen');
INSERT INTO gifi (accno,description) VALUES ('450', 'Energieaufwand zur Leistungserstellung');
INSERT INTO gifi (accno,description) VALUES ('460', 'Übriger Aufwand');
INSERT INTO gifi (accno,description) VALUES ('470', 'Direkte Einkaufsspesen');
INSERT INTO gifi (accno,description) VALUES ('480', 'Bestandesveränderungen Material- und Warenverluste');
INSERT INTO gifi (accno,description) VALUES ('490', 'Aufwandsminderung');
INSERT INTO gifi (accno,description) VALUES ('500', 'Personalaufwand');
INSERT INTO gifi (accno,description) VALUES ('540', 'Personalaufwand');
INSERT INTO gifi (accno,description) VALUES ('570', 'Sozialversicherungen');
INSERT INTO gifi (accno,description) VALUES ('580', 'Übriger Personalaufwand');
INSERT INTO gifi (accno,description) VALUES ('600', 'Raumaufwand');
INSERT INTO gifi (accno,description) VALUES ('610', 'Unterhalt und Ersatz');
INSERT INTO gifi (accno,description) VALUES ('620', 'Fahrzeug und Transport');
INSERT INTO gifi (accno,description) VALUES ('630', 'Versicherungen');
INSERT INTO gifi (accno,description) VALUES ('636', 'Abgaben, Gebühren, Bewilligungen');
INSERT INTO gifi (accno,description) VALUES ('640', 'Energie und Entsorgung');
INSERT INTO gifi (accno,description) VALUES ('650', 'Verwaltung');
INSERT INTO gifi (accno,description) VALUES ('656', 'Informatikaufwand');
INSERT INTO gifi (accno,description) VALUES ('660', 'Werbung');
INSERT INTO gifi (accno,description) VALUES ('670', 'Übriger Betriebsaufwand');
INSERT INTO gifi (accno,description) VALUES ('680', 'Finanzaufwand');
INSERT INTO gifi (accno,description) VALUES ('685', 'Finanzerfolg');
INSERT INTO gifi (accno,description) VALUES ('690', 'Abschreibungen');
INSERT INTO gifi (accno,description) VALUES ('700', 'Betriebliche Nebenerfolge');
INSERT INTO gifi (accno,description) VALUES ('740', 'Erfolg aus Finanzanlagen');
INSERT INTO gifi (accno,description) VALUES ('750', 'Erfolg betriebliche Liegenschaften');
INSERT INTO gifi (accno,description) VALUES ('790', 'Gewinne aus Veräusserung von betrieblichem Anlagevermögen');
INSERT INTO gifi (accno,description) VALUES ('800', 'Ausserordentlicher Ertrag');
INSERT INTO gifi (accno,description) VALUES ('801', 'Ausserordentlicher Aufwand');
INSERT INTO gifi (accno,description) VALUES ('820', 'Betriebsfremder Erfolg');
INSERT INTO gifi (accno,description) VALUES ('840', 'Ertrag betriebsfremde Finanzanlagen');
INSERT INTO gifi (accno,description) VALUES ('850', 'Erfolg betriebsfremde Liegenschaft');
INSERT INTO gifi (accno,description) VALUES ('870', 'Sonstiger betriebsfremder Ertrag');
INSERT INTO gifi (accno,description) VALUES ('801', 'Ausserordentlicher Aufwand');
INSERT INTO gifi (accno,description) VALUES ('890', 'Steuern');
INSERT INTO gifi (accno,description) VALUES ('900', 'Transferkonten');
