-- Schweizer Kontenrahmen KMU (Sterchi/Schweizer Gewerbeverband)
-- exkl. Konzern- und Tochtergesellschaften
-- ab SQL Ledger Version 2.8, einsprachig (deutsch)
-- Das Script löscht den bestehenden Kontenrahmen (falls vorhanden). 
-- Dieses Script nur bei Neuinstallationen bzw. Datenbanken ohne bestehende Buchungen durchführen.
-- integratio GmbH, September 2007

-- Diverse Anpassungen durch Run my Accounts AG, 2008-2014
-- Version 05.12.2014 Neues Rechnungslegungsrecht, Thomas Brändle, Mattia Kienast, Nils Samuelsson

-----------------
--- 1 AKTIVEN ---
-----------------
DELETE FROM chart;
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1','AKTIVEN','H','A','','1',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('10','UMLAUFVERMÖGEN','H','A','','100',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('100','FLÜSSIGE MITTEL','H','A','','100',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1000','Kasse','A','A','AR_paid:AP_paid','100',false,true,'kassa');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1020','Bank','A','A','AR_paid:AP_paid','100',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('106','KURZFRISTIG GEHALTENE AKTIVEN MIT BÖRSENKURS','H','A','','106',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('109','TRANSFERKONTO','H','A','','109',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1090','Transferkonto','A','A','AR_paid:AP_paid','109',false,true,'transfer');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1099','Unklare Beträge','A','A','AP_amount','109',false,true,'abklärung');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('110','FORDERUNGEN AUS LIEFERUNGEN UND LEISTUNGEN GEGENÜBER DRITTEN','H','A','','110',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1100','Forderungen Schweiz','A','A','AR','110',false,false,'forderungenschweiz');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1101','Forderungen Ausland','A','A','AR','110',false,false,'forderungenauslandchf');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1102','Forderungen Ausland Fremdwährungen','A','A','AR','110',false,false,'forderungenauslandandere');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1103','Forderungen FiBu','A','A','','110',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1109','Wertberichtigungen Forderungen aus Lieferungen und Leistungen gegenüber Dritten','A','A','','110',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('111','FORDERUNGEN AUS LIEFERUNGEN UND LEISTUNGEN GEGENÜBER BETEILIGUNGEN','H','A','','111',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1110','Forderungen aus Lieferungen und Leistungen gegenüber Beteiligungen','A','A','','111',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('114','ÜBRIGE KURZFRISTIGE FORDERUNGEN GEGENÜBER DRITTEN','H','A','','114',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('115','ÜBRIGE KURZFRISTIGE FORDERUNGEN GEGENÜBER BETEILIGUNGEN','H','A','','115',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('117','KURZFRISTIGE FORDERUNGEN GEGENÜBER STAATLICHEN STELLEN','H','A','','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1177','Forderungen gegenüber Oberzolldirektion','A','A','','117',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1179','Verrechnungssteuer','A','A','','117',false,true,'verrechnungssteuer');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('118','KURZFRISTIGE FORDERUNGEN GEGENÜBER SOZIALVERSICHERUNGEN','H','A','','118',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('119','SONSTIGE KURZFRISTIGE FORDERUNGEN','H','A','','119',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1192','Geleistete Anzahlungen','A','A','AP_paid','119',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('120','VORRÄTE UND NICHT FAKTURIERTE DIENSTLEISTUNGEN','H','A','','120',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1280','Nicht fakturierte Dienstleistungen','A','A','IC','120',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('130','AKTIVE RECHNUNGSABGRENZUNGEN','H','A','','130',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1300','Bezahlter Aufwand des Folgejahrs','A','A','','130',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1301','Noch nicht erhaltener Ertrag','A','A','','130',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1302','Arbeitgeberbeitragsreserve','A','A','','130',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('14','ANLAGEVERMÖGEN','H','A','','140',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('140','FINANZANLAGEN','H','A','','140',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1400','Wertschriften des Anlagevermögens','A','A','','140',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('144','LANGFRISTIGE FORDERUNGEN GEGENÜBER DRITTEN','H','A','','144',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1440','Darlehensforderungen gegenüber Dritten','A','A','','144',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('145','LANGFRISTIGE FORDERUNGEN GEGENÜBER BETEILIGUNGEN','H','A','','145',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1450','Darlehensforderungen gegenüber Beteiligungen','A','A','','145',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('148','BETEILIGUNGEN','H','A','','148',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1480','Beteiligungen','A','A','','148',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('150','MOBILE SACHANLAGEN','H','A','','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1500','Maschinen und Apparate','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1510','Mobiliar und Einrichtungen','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1520','Büromaschinen','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1530','Fahrzeuge','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1540','Werkzeuge und Geräte','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1590','Übrige mobile Sachanlagen','A','A','AP_amount','150',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('160','IMMOBILE SACHANLAGEN','H','A','','160',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1600','Immobile Sachanlagen','A','A','','160',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('170','IMMATERIELLE WERTE','H','A','','170',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1700','Patente, Marken, Lizenzen, Urheberrechte','A','A','AP_amount','170',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1740','Selber entwickelte Software','A','A','','170',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1741','Erworbene Software','A','A','AP_amount','170',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('1790','Übrige immaterielle Werte','A','A','','170',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2','PASSIVEN','H','L','','2',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('20','KURZFRISTIGES FREMDKAPITAL','H','L','','200',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('200','VERBINDLICHKEITEN AUS LIEFERUNGEN UND LEISTUNGEN','H','L','','200',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2000','Verbindlichkeiten aus Lieferungen und Leistungen','A','L','AP','200',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2001','Verbindlichkeiten aus Lieferungen und Leistungen FiBu','A','L','','200',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2002','Verbindlichkeiten für Personalaufwand','A','L','','200',false,true,'lohnzahlung');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('203','ERHALTENE ANZAHLUNGEN VON DRITTEN','H','L','','203',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2030','Erhaltene Anzahlungen von Dritten','A','L','AR_amount:IC_income','203',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('210','KURZFRISTIGE VERZINSLICHE VERBINDLICHKEITEN','H','L','','210',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('214','ÜBRIGE KURZFRISTIGE VERZINSLICHE VERBINDLICHKEITEN GEGENÜBER DRITTEN','H','L','','214',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('215','KURZFRISTIGE VERZINSLICHE VERBINDLICHKEITEN GEGENÜBER BETEILIGUNGEN','H','L','','215',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('220','KURZFRISTIGE VERBINDLICHKEITEN GEGENÜBER STAATLICHEN STELLEN','H','L','','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2200','Geschuldete MWST','A','L','AP_amount','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2206','Verrechnungssteuer','A','L','AP_amount','220',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('221','ÜBRIGE KURZFRISTIGE VERBINDLICHKEITEN GEGENÜBER DRITTEN (UNVERZINSLICH)','H','L','','221',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2215','Kreditkarte','A','L','','221',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('225','ÜBRIGE KURZFRISTIGE VERBINDLICHKEITEN GEGENÜBER BETEILIGUNGEN (UNVERZINSLICH)','H','L','','225',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('227','ÜBRIGE KURZFRISTIGE VERBINDLICHKEITEN GEGENÜBER SOZIALVERSICHERUNGEN UND VORSORGEEINRICHTUNGEN (UNVERZINSLICH)','H','L','','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2270','Kontokorrent Vorsorgeeinrichtung','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2271','Kontokorrent AHV, IV, EO, ALV','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2272','Kontokorrent FAK','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2273','Kontokorrent Unfallversicherung','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2274','Kontokorrent Krankentaggeldversicherung','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2279','Kontokorrent Quellensteuer','A','L','AP_amount','227',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('230','PASSIVE RECHNUNGSABGRENZUNG UND KURZFRISTIGE RÜCKSTELLUNGEN','H','L','','230',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2300','Noch nicht bezahlter Aufwand','A','L','','230',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2301','Erhaltener Ertrag des Folgejahrs','A','L','','230',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2330','Kurzfristige Rückstellungen','A','L','','230',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('24','LANGFRISTIGES FREMDKAPITAL','H','L','','240',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('240','LANGFRISTIGE VERZINSLICHE VERBINDLICHKEITEN','H','L','','240',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2400','Bankverbindlichkeiten langfristig','A','L','','240',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('245','ÜBRIGE LANGFRISTIGE VERZINSLICHE VERBINDLICHKEITEN GEGENÜBER DRITTEN','H','L','','245',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('247','LANGFRISTIGE VERZINSLICHE VERBINDLICHKEITEN GEGENÜBER BETEILIGUNGEN','H','L','','247',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('250','ÜBRIGE LANGFRISTIGE VERBINDLICHKEITEN GEGENÜBER DRITTEN (UNVERZINSLICH)','H','L','','250',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('255','ÜBRIGE LANGFRISTIGE VERBINDLICHKEITEN GEGENÜBER BETEILIGUNGEN (UNVERZINSLICH)','H','L','','255',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('260','RÜCKSTELLUNGEN SOWIE VOM GESETZ VORGESEHENE ÄHNLICHE POSITIONEN','H','L','','260',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('2600','Rückstellungen','A','L','','260',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3','BETRIEBLICHER ERTRAG AUS LIEFERUNGEN UND LEISTUNGEN','H','I','','3',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('30','PRODUKTIONSERLÖSE','H','I','','300',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3000','Produktionserlöse','A','I','AR_amount:IC_income','300',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('32','HANDELSERLÖSE','H','I','','320',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3200','Handelserlöse','A','I','AR_amount:IC_income','320',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('34','DIENSTLEISTUNGSERLÖSE','H','I','','340',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3400','Dienstleistungserlöse','A','I','AR_amount:IC_income','340',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('36','ÜBRIGE ERLÖSE AUS LIEFERUNGEN UND LEISTUNGEN','H','I','','360',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3600','Nebenerlöse aus Lieferungen und Leistungen','A','I','AR_amount:IC_income','360',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3680','Sonstige Erlöse','A','I','AR_amount:IC_income','360',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3689','Nicht kontiert','A','I','AR_amount','360',false,true,'nichtkontierterertrag');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3699','Systemkonto','A','I','AR_amount:IC_sale:IC_income','360',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('37','EIGENLEISTUNGEN UND EIGENVERBRAUCH','H','I','','370',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3700','Eigenleistungen','A','I','','370',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3710','Eigenverbrauch','A','I','','370',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('38','ERLÖSMINDERUNGEN','H','I','','380',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3800','Skonti','A','I','AR_paid','380',false,true,'debitorskonto');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3801','Rabatte und Preisnachlässe','A','I','AR_paid','380',false,true,'debitordifferenz');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3804','Inkassospesen','A','I','','380',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3805','Verluste Forderungen, Veränderung Wertberichtigungen','A','I','AR_amount:IC_income','380',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('39','BESTANDESÄNDERUNGEN AN UNFERTIGEN UND FERTIGEN ERZEUGNISSEN SOWIE AN NICHT FAKTURIERTEN DIENSTLEISTUNGEN','H','I','','390',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3900','Bestandesänderungen unfertige Erzeugnisse','A','I','','390',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3901','Bestandesänderungen fertige Erzeugnisse','A','I','','390',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('3904','Bestandesänderungen nicht fakturierte Dienstleistungen','A','I','','390',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4','AUFWAND FÜR MATERIAL, HANDLELSWAREN, DIENSTLEISTUNGEN UND ENERGIE','H','E','','400',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('40','MATERIALAUFWAND','H','E','','400',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4000','Materialeinkauf','A','E','AP_amount','400',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('42','HANDELSWARENAUFWAND','H','E','','420',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4200','Einkauf Handelsware','A','E','AP_amount','420',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('44','AUFWAND FÜR BEZOGENE DRITTLEISTUNGEN','H','E','','440',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4400','Einkauf Drittleistung','A','E','AP_amount','440',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('45','ENERGIEAUFWAND ZUR LEISTUNGSERSTELLUNG','H','E','','450',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('46','ÜBRIGER AUFWAND FÜR MATERIAL, HANDELSWAREN UND DIENSTLEISTUNGEN','H','E','','460',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('47','DIREKTE EINKAUFSSPESEN','H','E','','470',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('48','BESTANDESÄNDERUNGEN MATERIAL- / WARENVERLUSTE','H','E','','480',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4800','Bestandesänderungen Handelswaren','A','E','','480',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4880','Materialverluste','A','E','','480',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('49','EINKAUFSPREISMINDERUNGEN','H','E','','490',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('4999','Systemkonto','A','E','AP_amount:IC_expense:IC_cogs','490',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5','PERSONALAUFWAND','H','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5400','Löhne','A','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5401','Zulagen','A','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5402','Erfolgsbeteiligungen','A','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5403','Provisionen','A','E','','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5405','Leistungen von Sozialversicherungen','A','E','AP_amount','500',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('57','SOZIALVERSICHERUNGSAUFWAND','H','E','','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5700','AHV, IV, EO, ALV','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5710','FAK','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5720','Vorsorgeeinrichtungen','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5730','Unfallversicherung','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5740','Krankentaggeldversicherung','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5790','Quellensteuer','A','E','AP_amount','570',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('58','ÜBRIGER PERSONALAUFWAND','H','E','','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5800','Personalinserate','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5810','Aus- und Weiterbildung','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5820','Spesenentschädigung effektiv','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5830','Spesenentschädigung pauschal','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5840','Personalkantine','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5880','Sonstiger Personalaufwand','A','E','AP_amount','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5890','Privatanteile Personalaufwand','A','E','','580',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('59','LEISTUNGEN DRITTER','H','E','','590',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('5900','Leistungen Dritter','A','E','AP_amount','590',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6','ÜBRIGER BETRIEBLICHER AUFWAND, ABSCHREIBUNGEN UND WERTBERICHTIGUNGEN SOWIE FINANZERGEBNIS','H','E','','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('60','RAUMAUFWAND','H','E','','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6000','Mietzins','A','E','AP_amount','600',false,true,'miete');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6030','Nebenkosten','A','E','AP_amount','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6040','Reinigung','A','E','AP_amount','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6090','Privatanteile Raumaufwand','A','E','','600',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('61','UNTERHALT, REPARATUREN, ERSATZ (URE); LEASING MOBILE SACHANLAGEN','H','E','','610',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6130','URE Büromobiliar','A','E','AP_amount','610',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6160','Leasing mobile Sachanlagen','A','E','AP_amount','610',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('62','FAHRZEUG- UND TRANSPORTAUFWAND','H','E','','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6200','Reparaturen, Service, Reinigung Fahrzeuge','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6210','Betriebsstoffe Fahrzeuge','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6220','Versicherungen Fahrzeuge','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6230','Verkehrsabgaben, Beiträge, Gebühren','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6260','Fahrzeugleasing, Fahrzeugmieten','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6270','Privatanteil Fahrzeugaufwand','A','E','AR_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6280','Transportaufwand','A','E','AP_amount','620',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('63','SACHVERSICHERUNGEN, ABGABEN, GEBÜHREN, BEWILLIGUNGEN','H','E','','630',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6300','Sachversicherungen','A','E','AP_amount','630',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6360','Abgaben und Gebühren','A','E','AP_amount','630',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6370','Bewilligungen','A','E','AP_amount','630',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('64','ENERGIE- UND ENTSORGUNGSAUFWAND','H','E','','640',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6400','Elektrizität','A','E','AP_amount','640',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6460','Entsorgungsaufwand','A','E','AP_amount','640',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('65','VERWALTUNGS- UND INFORMATIKAUFWAND','H','E','','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('650','VERWALTUNGSAUFWAND','H','E','','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6500','Büromaterial','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6501','Drucksachen','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6503','Fachliteratur','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6510','Telekommunikation','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6513','Porti','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6520','Beiträge, Spenden, Vergabungen, Trinkgelder','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6530','Buchführung','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6531','Unternehmensberatung','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6532','Rechtsberatung','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6540','Verwaltungsrat, Generalversammlung','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6542','Revisionsstelle','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6550','Gründungs-, Kapitalerhöhungs- und Organisationsaufwand','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6551','Inkasso- und Betreibungsaufwand','A','E','AP_amount','650',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('657','INFORMATIKAUFWAND','H','E','','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6570','Leasing Hardware und Software','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6580','Lizenzen, Updates','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6581','Hosting und Wartung','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6583','Verbrauchsmaterial IT','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6590','Beratung und Entwicklung IT','A','E','AP_amount','657',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('66','WERBEAUFWAND','H','E','','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6600','Werbeinserate','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6610','Werbedrucksachen, Werbematerial, Muster','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6620','Fachmessen, Ausstellungen, Dekoration','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6640','Reisespesen','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6641','Kundenbetreuung','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6660','Sponsoring','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6670','Öffentlichkeitsarbeit, Public Relations','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6680','Werbeberatung, Marktanalysen','A','E','AP_amount','660',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('67','SONSTIGER BETRIEBLICHER AUFWAND','H','E','','670',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6700','Sonstiger betrieblicher Aufwand','A','E','AP_amount','670',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6799','Nicht kontiert','A','E','AP_amount','670',false,true,'nichtkontierteraufwand');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('68','ABSCHREIBUNGEN UND WERTBERICHTIGUNGEN','H','E','','680',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6800','Wertberichtigungen','A','E','','680',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6820','Abschreibungen','A','E','','680',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('690','FINANZAUFWAND','H','E','','690',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6900','Zinsaufwand gegenüber Dritten','A','E','AP_amount','690',false,true,'schuldzins');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6930','Zinsaufwand gegenüber Vorsorgeeinrichtungen','A','E','AP_amount','690',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6940','Bankspesen','A','E','AR_paid:AP_paid','690',false,true,'drittspesen');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6942','Kursverluste','A','E','','690',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6943','Kreditkartengebühr','A','E','AP_amount','690',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6944','Bankspesen Zahlungsverkehr, Rundungsdifferenzen','A','E','AP_paid','690',false,true,'kreditordifferenz');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('695','FINANZERTRAG','H','E','','695',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6950','Erträge aus flüssigen Mitteln und Wertschriften','A','E','','695',false,true,'guthabenzins');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('6952','Kursgewinne','A','E','','695',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('7','BETRIEBLICHER NEBENERFOLG','H','E','','700',false,false,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('700','ERTRAG AUS NEBENBETRIEBEN','H','E','','700',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('7000','Ertrag aus Nebenbetrieb','A','E','','700',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('701','AUFWAND AUS NEBENBETRIEBEN','H','E','','701',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('7010','Aufwand aus Nebenbetrieb','A','E','','701',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8','AUSSERORDENTLICHER UND BETRIEBSFREMDER ERFOLG, STEUERN','H','E','','800',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('800','BETRIEBSFREMDER AUFWAND','H','E','','800',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8000','Betriebsfremder Aufwand','A','E','','800',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('810','BETRIEBSFREMDER ERTRAG','H','E','','810',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8100','Betriebsfremder Ertrag','A','E','','810',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('850','AUSSERORDENTLICHER AUFWAND','H','E','','850',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8500','Ausserordentlicher Aufwand','A','E','AP_amount','850',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('851','AUSSERORDENTLICHER ERTRAG','H','E','','851',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8510','Ausserordentlicher Ertrag','A','E','AR_amount:AP_amount','851',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('860','EINMALIGER AUFWAND','H','E','','860',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8600','Einmaliger Aufwand','A','E','','860',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('861','EINMALIGER ERTRAG','H','E','','861',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8610','Einmaliger Ertrag','A','E','','861',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('870','PERIODENFREMDER AUFWAND','H','E','','870',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8700','Periodenfremder Aufwand','A','E','','870',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('871','PERIODENFREMDER ERTRAG','H','E','','871',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8710','Periodenfremder Ertrag','A','E','','871',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('89','DIREKTE STEUERN','H','E','','890',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8900','Kantons- und Gemeindesteuern','A','E','AP_amount','890',false,true,'');
insert into chart (accno,description,charttype,category,link,gifi_accno,contra,allow_gl,symbol_link) values ('8901','Direkte Bundessteuern','A','E','AP_amount','890',false,true,'');