-- Schweizer Kontenrahmen KMU (Sterchi/Schweizer Gewerbeverband)
-- exkl. Konzern- und Tochtergesellschaften
-- ab SQL Ledger Version 2.8, einsprachig (deutsch)
-- Das Script löscht den bestehenden Kontenrahmen (falls vorhanden). 
-- Dieses Script nur bei Neuinstallationen bzw. Datenbanken ohne bestehende Buchungen durchführen.
-- integratio GmbH, September 2007

-- Diverse Anpassungen durch Run my Accounts AG, 2008-2014
-- Version 05.12.2014 Neues Rechnungslegungsrecht, Thomas Brändle, Mattia Kienast, Nils Samuelsson

-----------------
--- 1 AKTIVEN ---
-----------------
DELETE FROM chart;
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1', 'ACTIFS', 'H', 'A', '', '1', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('10', 'ACTIFS CIRCULANTS', 'H', 'A', '', '100', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('106', 'ACTIFS COSTÉS EN BOURSE DÉTENUS À COURT TERME', 'H', 'A', '', '106', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1000', 'Caisse', 'A', 'A', 'AR_paid:AP_paid', '100', 'f', 't', 'kassa');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1109', 'Corrections de la valeur des ventes de biens et de prestations de services (incl. ducroire)', 'A', 'A', '', '110', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1020', 'Banque', 'A', 'A', 'AR_paid:AP_paid', '100', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('109', 'COMPTES D`ATTENTE', 'H', 'A', '', '109', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1090', 'Comptes de transfert', 'A', 'A', 'AR_paid:AP_paid', '109', 'f', 't', 'transfer');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1099', 'Compte d'' attente pour des montants à clarifier', 'A', 'A', 'AP_amount', '109', 'f', 't', 'abklärung');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('110', 'CRÉANCES RÉSULTANT DE LA VENTE DE BIENS ET DE PRESTATIONS DE SERVICES', 'H', 'A', '', '110', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6513', 'Frais de port', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('114', 'AUTRES CRÉANCES À COURT TERME', 'H', 'A', '', '114', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1110', 'Créances envers la participation A', 'A', 'A', '', '111', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('111', 'CRÉANCES RÉSULTANT DE LA VENTE DE BIENS ET DE PRESTATIONS DE SERVICES ENVERS DES PARTICIPATIONS', 'H', 'A', '', '111', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1177', 'Créances envers I`administration des douanes', 'A', 'A', '', '117', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('115', 'AUTRES CRÉANCES À COURT TERME ENVERS DES PARTICIPATIONS', 'H', 'A', '', '115', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('117', 'CRÉANCES À COURT TERME ENVERS DES INSTITUTIONS PUBLIQUES', 'H', 'A', '', '117', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('118', 'CRÉANCES À COURT TERME ENVERS LES ASSURANCES SOCIALES ET LES INSTITUTIONS DE PRÉVOYANCE PROFESSIONNELLE', 'H', 'A', '', '118', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('119', 'AUTRES CRÉANCES À COURT TERME', 'H', 'A', '', '119', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('120', 'STOCKS ET PRESTATIONS DE SERVICES NON FACTURÉES', 'H', 'A', '', '120', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1192', 'Acomptes payés', 'A', 'A', 'AP_paid', '119', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1280', 'Travaux en cours', 'A', 'A', 'IC', '120', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('130', 'ACTIFS DE RÉGULARISATION (ACTIFS TRANSITOIRES)', 'H', 'A', '', '130', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1300', 'Charges payées d‘avance', 'A', 'A', '', '130', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1301', 'Produits à recevoir', 'A', 'A', '', '130', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1302', 'Réserve de contributions de I` employeur', 'A', 'A', '', '130', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('14', 'ACTIFS IMMOBILISÉS', 'H', 'A', '', '140', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('140', 'IMMOBILISATIONS FINANCIÈRES', 'H', 'A', '', '140', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1400', 'Actions', 'A', 'A', '', '140', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1450', 'Prêts envers la participation A', 'A', 'A', '', '145', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1440', 'Prêts', 'A', 'A', '', '144', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('144', 'CRÉANCES À LONG TERME ENVERS DES TIERS', 'H', 'A', '', '144', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('145', 'CRÉANCES À LONG TERME ENVERS DES PARTICIPATIONS', 'H', 'A', '', '145', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('148', 'PARTICIPATIONS', 'H', 'A', '', '148', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('150', 'IMMOBILISATIONS CORPORELLES MEUBLES', 'H', 'A', '', '150', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('210', 'DETTES À COURT TERME PORTANT INTÉRÊT', 'H', 'L', '', '210', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1500', 'Machines et appareils', 'A', 'A', 'AP_amount', '150', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1510', 'Mobilier et installations', 'A', 'A', 'AP_amount', '150', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1520', 'Machines de bureau', 'A', 'A', 'AP_amount', '150', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1530', 'Véhicule A', 'A', 'A', 'AP_amount', '150', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1590', 'Lingerie et habits de travail', 'A', 'A', 'AP_amount', '150', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1540', 'Outillages et appareils', 'A', 'A', 'AP_amount', '150', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('160', 'IMMOBILISATIONS CORPORELLES IMMEUBLES', 'H', 'A', '', '160', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1600', 'Immeubles d’exploitation', 'A', 'A', '', '160', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('170', 'IMMOBILISATIONS INCORPORELLES', 'H', 'A', '', '170', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1700', 'Brevets', 'A', 'A', 'AP_amount', '170', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1740', 'Logiciels développés en interne', 'A', 'A', '', '170', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1741', 'Logiciels achetés', 'A', 'A', 'AP_amount', '170', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1790', 'Autres immobilisations incorporelles', 'A', 'A', '', '170', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2', 'PASSIFS', 'H', 'L', '', '2', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('20', 'CAPITAUX ÉTRANGERS À COURT TERME', 'H', 'L', '', '200', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2002', 'Dettes résultant de charges de personnel', 'A', 'L', '', '200', 'f', 't', 'lohnzahlung');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('200', 'DETTES À COURT TERME RÉSULTANT DE I`ACHAT DE BIENS ET DE PRESTATIONS DE SERVICES', 'H', 'L', '', '200', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2001', 'Dettes résultant de prestations de services de tiers', 'A', 'L', '', '200', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('203', 'ACOMPTES DE TIERS', 'H', 'L', '', '203', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2030', 'Acomptes de tiers', 'A', 'L', 'AR_amount:IC_income', '203', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1103', 'Créances Comptabilité Financière', 'A', 'A', '', '110', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('220', 'AUTRES DETTES À COURT TERME', 'H', 'L', '', '220', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('214', 'AUTRES DETTES FINANCIÈRES À COURT TERME ENVERS DES TIERS', 'H', 'L', '', '214', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('215', 'DETTES FINANCIÈRES À COURT TERME ENVERS DES PARTICIPATIONS', 'H', 'L', '', '215', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2200', 'TVA due', 'A', 'L', 'AP_amount', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2206', 'Impôt anticipé à payer', 'A', 'L', 'AP_amount', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('227', 'AUTRES DETTES À COURT TERME RELATIVES AUX CHARGES SALARIALES (SANS INTÉRÊTS)', 'H', 'L', '', '227', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('221', 'AUTRES DETTES À COURT TERME ENVERS DES TIERS (SANS INTÉRÊTS)', 'H', 'L', '', '221', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('225', 'AUTRES DETTES À COURT TERME ENVERS DES PARTICIPATIONS (SANS INTÉRÊTS)', 'H', 'L', '', '225', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2270', 'Compte courant Institutions de prévoyance professionnelle', 'A', 'L', 'AP_amount', '227', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2271', 'Compte courant AVS, AI, APG, AC', 'A', 'L', 'AP_amount', '227', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2272', 'Compte courant Caisse d'' allocations familiales (CAF)', 'A', 'L', 'AP_amount', '227', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2273', 'Compte courant Assurance-accidents', 'A', 'L', 'AP_amount', '227', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2300', 'Charges à payer', 'A', 'L', '', '230', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2274', 'Compte courant Assurance maladie (indemnité journalière maladie)', 'A', 'L', 'AP_amount', '227', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2279', 'Compte courant Impôt à la source', 'A', 'L', 'AP_amount', '227', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2301', 'Produits encaissés d’avance', 'A', 'L', '', '230', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2330', 'Provisions pour travaux de garantie', 'A', 'L', '', '230', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('24', 'CAPITAUX ÉTRANGERS À LONG TERME', 'H', 'L', '', '240', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('240', 'DETTES À LONG TERME PORTANT INTÉRÊT', 'H', 'L', '', '240', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2400', 'Emprunts A (Dettes bancaires à long terme)', 'A', 'L', '', '240', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('245', 'AUTRES DETTE À LONG TERMA À I`ÉGARD DE TIERS PORTANT INTÉRÊT', 'H', 'L', '', '245', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('247', 'DETTES À LONG TERME DES PARTICIPATIONS', 'H', 'L', '', '247', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('250', 'AUTRES DETTES À LONG TERME', 'H', 'L', '', '250', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1480', 'Participation A', 'A', 'A', '', '148', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('100', 'TRÉSORERIE', 'H', 'A', '', '100', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1179', 'Impôt anticipé à récupérer', 'A', 'A', '', '117', 'f', 't', 'verrechnungssteuer');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2215', 'Cartes de crédit', 'A', 'L', '', '221', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('260', 'PROVISIONS ET POSTES ANALOGUES PRÉVUS PAR LA LOI', 'H', 'L', '', '260', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3', 'PRODUITS NETS DES VENTES DE BIENS ET DE PRESTATIONS DE SERVICES', 'H', 'I', '', '3', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('30', 'CHIFFRE D`AFFAIRES DE LA PRODUCTION VENDUE', 'H', 'I', '', '300', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3200', 'Ventes de marchandises', 'A', 'I', 'AR_amount:IC_income', '320', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('32', 'VENTES DE MARCHANDISES', 'H', 'I', '', '320', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('34', 'VENTES DE PRESTATIONS', 'H', 'I', '', '340', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3700', 'Prestations propres', 'A', 'I', '', '370', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3710', 'Propres consommations', 'A', 'I', '', '370', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3680', 'Autres produits', 'A', 'I', 'AR_amount:IC_income', '360', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('37', 'PROPRES PRESTATIONS ET PROPRES CONSOMMATIONS', 'H', 'I', '', '370', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3904', 'Variation de la valeur des prestations non facturées', 'A', 'I', '', '390', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2600', 'Provisions', 'A', 'L', '', '260', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3400', 'Ventes de prestations', 'A', 'I', 'AR_amount:IC_income', '340', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('38', 'DÉDUCTIONS SUR VENTES', 'H', 'I', '', '380', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3804', 'Frais d`encaissement', 'A', 'I', '', '380', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3800', 'Escomptes', 'A', 'I', 'AR_paid', '380', 'f', 't', 'debitorskonto');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3805', 'Pertes sur clients, variation du ducroire', 'A', 'I', 'AR_amount:IC_income', '380', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('39', 'VARIATION DES STOCKS DE PRODUITS FINIS ET SEMI-FINIS ET VARIATION DES PRESTATIONS DE SERVICES NON FACTURÉS', 'H', 'I', '', '390', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3900', 'Variation des stocks de produits semi-finis', 'A', 'I', '', '390', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3901', 'Variation des stocks de produits finis', 'A', 'I', '', '390', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('4', 'CHARGES DE MATÉRIEL, DE MARCHANDISES, DE PRESTATIONS DE TIERS ET D`ÉNERGIE', 'H', 'E', '', '400', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('4400', 'Charges pour prestations de services', 'A', 'E', 'AP_amount', '440', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('40', 'Charges de matériel', 'H', 'E', '', '400', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('4200', 'Charges de marchandise', 'A', 'E', 'AP_amount', '420', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('42', 'CHARGES DE MARCHANDISES', 'H', 'E', '', '420', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('44', 'PRESTATIONS ET TRAVAUX DE TIERS', 'H', 'E', '', '440', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5820', 'Indemnités effectives', 'A', 'E', 'AP_amount', '580', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('46', 'AUTRES CHARGES POUR MATÉRIEL, MARCHANDISES ET PRESTATIONS DE TIERS', 'H', 'E', '', '460', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('47', 'CHARGES DIRECTES D''ACHAT', 'H', 'E', '', '470', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('48', 'VARIATION DES STOCKS, PERTES DE MATIÈRES ET DE MARCHANDISES', 'H', 'E', '', '480', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('4800', 'Variation des stocks de marchandises', 'A', 'E', '', '480', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('4880', 'Pertes de matières', 'A', 'E', '', '480', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('49', 'DÉDUCTIONS OBTENUES SUR ACHATS', 'H', 'E', '', '490', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5', 'CHARGES DE PERSONNEL', 'H', 'E', '', '500', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5400', 'Salaires', 'A', 'E', '', '500', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5401', 'Indemnités', 'A', 'E', '', '500', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5402', 'Participations au bénéfice', 'A', 'E', '', '500', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5403', 'Commissions', 'A', 'E', '', '500', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5405', 'Prestations des assurances sociales', 'A', 'E', 'AP_amount', '500', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('57', 'CHARGES SOCIALES', 'H', 'E', '', '570', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5700', 'AVS, AI, APG, AC', 'A', 'E', 'AP_amount', '570', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5710', 'Caisse d''allocations familiales (CAF)', 'A', 'E', 'AP_amount', '570', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5730', 'Assurance-accidents', 'A', 'E', 'AP_amount', '570', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5740', 'Assurance maladie (indemnité journalière maladie)', 'A', 'E', 'AP_amount', '570', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5790', 'Impôts à la source', 'A', 'E', 'AP_amount', '570', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('58', 'AUTRES CHARGES DE PERSONNEL', 'H', 'E', '', '580', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5800', 'Annonces pour recherche de personnel', 'A', 'E', 'AP_amount', '580', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5830', 'Indemnités forfaitaires', 'A', 'E', 'AP_amount', '580', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5880', 'Autres charges de personnel', 'A', 'E', 'AP_amount', '580', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5840', 'Repas au restaurant d''entreprise', 'A', 'E', 'AP_amount', '580', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('59', 'PRESTATIONS DE TIERS', 'H', 'E', '', '590', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5890', 'Parts privées sur charges de personnel', 'A', 'E', '', '580', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6000', 'Loyer', 'A', 'E', 'AP_amount', '600', 'f', 't', 'miete');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5900', 'Prestations de tiers', 'A', 'E', 'AP_amount', '590', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('60', 'CHARGES DE LOCAUX', 'H', 'E', '', '600', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6030', 'Charges accessoires', 'A', 'E', 'AP_amount', '600', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6040', 'Nettoyage', 'A', 'E', 'AP_amount', '600', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6160', 'leasing immobilisations corporelles mobiles', 'A', 'E', 'AP_amount', '610', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6090', 'Parts privées sur charges de chauffage, d''éclairage, de nettoyage', 'A', 'E', '', '600', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6130', 'ERR mobilier de bureau', 'A', 'E', 'AP_amount', '610', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('62', 'CHARGES DE VÉHICULES ET DE TRANSPORT', 'H', 'E', '', '620', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6220', 'Assurances de véhicules', 'A', 'E', 'AP_amount', '620', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6210', 'Carburants de véhicules', 'A', 'E', 'AP_amount', '620', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6230', 'Taxes de circulation, cotisations, taxes', 'A', 'E', 'AP_amount', '620', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6260', 'Leasing et location de véhicules', 'A', 'E', 'AP_amount', '620', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6280', 'Charges de transport', 'A', 'E', 'AP_amount', '620', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6270', 'Parts privées sur charges de véhicules', 'A', 'E', 'AR_amount', '620', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6300', 'Assurances-choses', 'A', 'E', 'AP_amount', '630', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('63', 'ASSURANCES-CHOSES, DROITS, TAXES, AUTORISATIONS', 'H', 'E', '', '630', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6400', 'Electricité', 'A', 'E', 'AP_amount', '640', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6360', 'Droits et Taxes', 'A', 'E', 'AP_amount', '630', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6370', 'Autorisations', 'A', 'E', 'AP_amount', '630', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('64', 'CHARGES D''ÉNERGIE ET ÉVACUATION DES DÉCHETS', 'H', 'E', '', '640', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6460', 'Evacuation des déchets', 'A', 'E', 'AP_amount', '640', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6510', 'Téléphone et Internet', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('65', 'CHARGES D''ADMINISTRATION ET D''INFORMATIQUE', 'H', 'E', '', '650', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('650', 'CHARGES D''ADMINISTRATION', 'H', 'E', '', '650', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6500', 'Matériel du bureau', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6501', 'Imprimés', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6503', 'Littérature spécialisée, journaux, magazines', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3689', 'Non imputé', 'A', 'I', 'AR_amount', '360', 'f', 't', 'nichtkontierterertrag');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('4000', 'Charges de matériel', 'A', 'E', 'AP_amount', '400', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6200', 'Réparation, Service, Nettoyage de véhicules', 'A', 'E', 'AP_amount', '620', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3000', 'Ventes de produits fabriqués', 'A', 'I', 'AR_amount:IC_income', '300', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3699', 'Compte de système', 'A', 'I', 'AR_amount:IC_income:IC_sale', '360', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('4999', 'Compte de système', 'A', 'E', 'AP_amount:IC_expense:IC_cogs', '490', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6943', 'Frais de cartes de crédit', 'A', 'E', 'AP_amount', '690', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6944', 'Frais bancaires pour opérations de paiement, différences d''arrondis', 'A', 'E', 'AP_paid', '690', 'f', 't', 'kreditordifferenz');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6950', 'Produits financiers sur trésorerie et titres', 'A', 'E', '', '695', 'f', 't', 'guthabenzins');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6952', 'Gains de change', 'A', 'E', '', '695', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1120', 'Créances envers I`actionnaire A', 'A', 'A', '', '112', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('116', 'AUTRES CRÉANCES À COURT TERME ENVERS LES PARTIES PRENANTES ET LES ORGANES', 'H', 'A', '', '116', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1173', 'Impôt préalable 8% sur investissements et autres charges d''exploitation', 'A', 'A', 'AP_tax', '117', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6799', 'Non imputé', 'A', 'E', 'AP_amount', '670', 'f', 't', 'nichtkontierteraufwand');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('146', 'CRÉANCES À LONG TERME ENVERS LES PARTIES PRENANTES ET LES ORGANES', 'H', 'A', '', '146', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1460', 'Prêts envers I`actionnaire A', 'A', 'A', '', '146', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('18', 'CAPITAL SOCIAL (OU CAPITAL DE FONDATION) NON LIBÉRÉ', 'H', 'A', '', '180', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1170', 'Impôt préalable 8% sur matériel, marchandises, prestations et énergie', 'A', 'A', 'AP_tax', '117', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('216', 'DETTES FINANCIÈRES À COURT TERME ENVERS LES PARTIES PRENANTES ET LES ORGANES', 'H', 'L', '', '216', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2160', 'Dettes envers I`actionnaire A', 'A', 'L', 'AR_paid:AP_paid', '216', 'f', 't', 'kontokorrent');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('226', 'AUTRES DETTES FINANCIÈRES À COURT TERME ENVERS LES PARTIES PRENANTES ET LES ORGANES (SANS INTÉRÊTS)', 'H', 'L', '', '226', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2261', 'Dividendes', 'A', 'L', '', '226', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('248', 'DETTES À LONG TERME AUPRÈS DES PARTIES PRENANTES ET DES ORGANES', 'H', 'L', '', '248', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('256', 'AUTRES DETTES FINANCIÈRES À LONG TERME ENVERS LES PARTIES PRENANTES ET LES ORGANES (SANS INTÉRÊTS)', 'H', 'L', '', '256', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('28', 'CAPITAUX PROPRES (PERSONNES MORALES)', 'H', 'Q', '', '280', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('280', 'CAPITA SOCIAL (CAPITAL-ACTIONS, CAPITAL DE FONDATION, CAPITAL PROPRE)', 'H', 'Q', '', '280', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2800', 'Capital-actions catégorie A', 'A', 'Q', '', '280', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2900', 'Agio à la fondation au lors d`augmentations de capital', 'A', 'Q', '', '290', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2950', 'Réserves légales issue du bénéfice', 'A', 'Q', '', '290', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2960', 'Réserves libre', 'A', 'Q', '', '290', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('297', 'BÉNÉFICE OU PERTE RÉSULTANT DU BILAN', 'H', 'Q', '', '297', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2970', 'Bénéfice ou perte reporté', 'A', 'Q', '', '297', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2979', 'Bénéfice ou perte de l’exercice', 'A', 'Q', '', '297', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('298', 'PROPRES ACTIONS, PARTS SOCIALES', 'H', 'Q', '', '298', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6581', 'Hosting et maintenance', 'A', 'E', 'AP_amount', '657', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6530', 'Honoraires pour la tenue de la comptabilité', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6531', 'Honoraires pour conseil en gestion d''entreprise', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6540', 'Charges du conseil d''administration, Charges de l''assemblée générale', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6542', 'Charges de l''organe de révision', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6551', 'Frais de recouvrement', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('657', 'FRAIS INFORMATIQUES', 'H', 'E', '', '657', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6570', 'Leasing hardware et software', 'A', 'E', 'AP_amount', '657', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6580', 'Charges de licences et de mises à jour', 'A', 'E', 'AP_amount', '657', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6590', 'Conseils et développements IT', 'A', 'E', 'AP_amount', '657', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6583', 'Consommables IT', 'A', 'E', 'AP_amount', '657', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('66', 'CHARGES DE PUBLICITÉ', 'H', 'E', '', '660', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('700', 'PRODUITS ACCESSOIRES', 'H', 'E', '', '700', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6600', 'Publicité dans les journaux', 'A', 'E', 'AP_amount', '660', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6610', 'Imprimés publicitaires, matériel de publicité, échantillons', 'A', 'E', 'AP_amount', '660', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6620', 'Foires, expositions, décoration', 'A', 'E', 'AP_amount', '660', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6640', 'Frais de déplacement', 'A', 'E', 'AP_amount', '660', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6641', 'Service à la clientèle', 'A', 'E', 'AP_amount', '660', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6660', 'Sponsoring', 'A', 'E', 'AP_amount', '660', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6670', 'Relations publiques', 'A', 'E', 'AP_amount', '660', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('67', 'AUTRES CHARGES D''EXPLOITATION', 'H', 'E', '', '670', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6700', 'Autres charges d''exploitation', 'A', 'E', 'AP_amount', '670', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6820', 'Amortissement', 'A', 'E', '', '680', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6800', 'Ajustement de la valeur', 'A', 'E', '', '680', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('68', 'AMORTISSEMENTS ET CORRECTIONS DE LA VALEUR', 'H', 'E', '', '680', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('690', 'CHARGES FINANCIÈRES', 'H', 'E', '', '690', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6940', 'Frais bancaires', 'A', 'E', 'AR_paid:AP_paid', '690', 'f', 't', 'drittspesen');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6920', 'Charge d''intérêts envers les parties prenantes et les organes', 'A', 'E', 'AP_amount', '690', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6900', 'Intérêts débiteurs envers la troisième', 'A', 'E', 'AP_amount', '690', 'f', 't', 'schuldzins');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6942', 'Pertes de change', 'A', 'E', '', '690', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('695', 'PRODUITS FINANCIERS', 'H', 'E', '', '695', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('7', 'RÉSULTAT DES ACTIVITÉS ANNEXES D''EXPLOITATION', 'H', 'E', '', '700', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('7000', 'Produits accessoires', 'A', 'E', '', '700', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('701', 'CHARGES ACCESSOIRES', 'H', 'E', '', '701', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2980', 'Propres actions', 'A', 'Q', '', '298', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8', 'RÉSULTATS EXCEPTIONNELS ET HORS EXPLOITATION', 'H', 'E', '', '800', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('800', 'CHARGES HORS EXPLOITATION', 'H', 'E', '', '800', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8000', 'Charges hors exploitation', 'A', 'E', '', '800', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('810', 'PRODUITS HORS EXPLOITATION', 'H', 'E', '', '810', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8100', 'Produits hors exploitation', 'A', 'E', '', '810', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('850', 'CHARGES EXCEPTIONNELLES', 'H', 'E', '', '850', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8500', 'Charges exceptionnelles', 'A', 'E', 'AP_amount', '850', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('851', 'PRODUITS EXCEPTIONNELS', 'H', 'E', '', '851', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8510', 'Produits exceptionnels', 'A', 'E', 'AR_amount:AP_amount', '851', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('860', 'CHARGES UNIQUES', 'H', 'E', '', '860', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8600', 'Charges uniques', 'A', 'E', '', '860', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('861', 'PRODUITS UNIQUES', 'H', 'E', '', '861', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8610', 'Produits uniques', 'A', 'E', '', '861', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('870', 'CHARGES HORS PÉRIODE', 'H', 'E', '', '870', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8700', 'Charges hors période', 'A', 'E', '', '870', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('871', 'PRODUITS HORS PÉRIODE', 'H', 'E', '', '871', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8710', 'Produits hors période', 'A', 'E', '', '871', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('89', 'IMPÔTS DIRECTS', 'H', 'E', '', '890', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8900', 'impôts cantonaux et communaux', 'A', 'E', 'AP_amount', '890', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('8901', 'Impôts fédéreaux', 'A', 'E', 'AP_amount', '890', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('7010', 'Charges accessoires', 'A', 'E', '', '701', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6520', 'Cotisations, dons, cadeaux et pourboires', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1800', 'Capital-actions non libéré', 'A', 'A', '', '180', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1100', 'Créances suisses en CHF', 'A', 'A', 'AR', '110', 'f', 'f', 'forderungenschweiz');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1174', 'Impôt préalable 3.8% sur investissements et autres charges d''exploitation', 'A', 'A', 'AP_tax', '117', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1101', 'Créances étrangères en CHF', 'A', 'A', 'AR', '110', 'f', 'f', 'forderungenauslandchf');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1102', 'Créances étrangères en monnaie étrangère A', 'A', 'A', 'AR', '110', 'f', 'f', 'forderungenauslandandere');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('112', 'CRÉANCES RÉSULTANT DE LA VENTE DE BIENS ET DE PRESTATIONS DE SERVICES ENVERS LES PARTIES PRENANTES ET LES ORGANES', 'H', 'A', '', '112', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1175', 'Impôt préalable 2.5% sur investissements et autres charges d''exploitation', 'A', 'A', 'AP_tax', '117', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('22055', 'Éléments n’ayant pas valeur de contre-prestations TVA 0%', 'A', 'L', '', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2000', 'Dettes résultant d’achats et de matières et de marchandises', 'A', 'L', 'AP', '200', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('230', 'PASSIFS DE RÉGULARISATION (PASSIFS TRANSITOIRES) ET PROVISIONS À COURT TERME', 'H', 'L', '', '230', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('255', 'AUTRES DETTES À LONG TERME ENVERS DES PARTICIPATIONS (SANS INTÉRÊTS)', 'H', 'L', '', '255', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('290', 'RÊSERVES ET BÉNÉFICE REPORTÉ OU PERTE REPORTÉE', 'H', 'Q', '', '290', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('36', 'PRODUITS ANNEXES RÉSULTANT DE LA VENTE DE BIENS ET DE PRESTATIONS DE SERVICES', 'H', 'I', '', '360', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3801', 'Rabais et réductions de prix', 'A', 'I', 'AR_paid', '380', 'f', 't', 'debitordifferenz');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('45', 'CHARGES D''ÉNERGIE POUR L''EXPLOITATION', 'H', 'E', '', '450', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5720', 'Prévoyance professionnelle', 'A', 'E', 'AP_amount', '570', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6', 'AUTRES CHARGES D''EXPLOITATION, AMORTISSEMENTS ET CORRECTIONS DE VALEUR, RÉSULTAT FINANCIER', 'H', 'E', '', '600', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6532', 'Honoraires pour conseil juridique', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6550', 'Frais de fondation, d''augmentation de capital er d''organisation', 'A', 'E', 'AP_amount', '650', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6680', 'Conseils en publicité, Etudes de marché', 'A', 'E', 'AP_amount', '660', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('6930', 'Charge d''intérêts envers des institutions de prévoyance professionnelle', 'A', 'E', 'AP_amount', '690', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('5810', 'Formation obligatoire/continue', 'A', 'E', 'AP_amount', '580', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('61', 'ENTRETIEN, RÉPARATIONS, REMPLACEMENTS (ERR); LEASING IMMOBILISATIONS CORPORELLES MOBILES', 'H', 'E', '', '610', 'f', 'f', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('3600', 'Produits annexes résultant de livraisons et de prestations de services', 'A', 'I', 'AR_amount:IC_income', '360', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('22050', 'Prestations exonérées, exportations TVA 0% (Chiffre. 220)', 'A', 'L', '', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('22051', 'Prestations fournies à l’étranger TVA 0% (Chiffre. 221)', 'A', 'L', '', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('22052', 'Prestations exclues du champ de l’impôt TVA 0% (Chiffre. 230)', 'A', 'L', '', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('22053', 'Subventions TVA 0% (Chiffre. 900)', 'A', 'L', '', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('22054', 'Les dons, les dividendes, les dédommagements TVA 0% (Chiffre. 910)', 'A', 'L', '', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2201', 'TVA 8%', 'A', 'L', 'AR_tax:IC_taxpart:IC_taxservice', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2202', 'TVA 3.8%', 'A', 'L', 'AR_tax:IC_taxpart:IC_taxservice', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2203', 'TVA 2.5%', 'A', 'L', 'AR_tax:IC_taxpart:IC_taxservice', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('2204', 'Impôt sur les acquisitions 8.0%', 'A', 'L', 'AP_tax', '220', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1176', 'Impôt sur les acquisitions 8,0%', 'A', 'A', 'AP_tax', '117', 'f', 't', '');
INSERT INTO chart(accno, description, charttype, category, "link", gifi_accno, contra, allow_gl, symbol_link) VALUES ('1172', 'Impôt préalable 2.5% sur matériel, marchandises, prestations et énergie', 'A', 'A', 'AP_tax', '117', 'f', 't', '');

